### ISSUE TITLE
Are subscript captures correct?

### ISSUE THREAD

**Issue by levouh** [milisims/tree-sitter-org#12]
Never messed with the actual parsers myself so not entirely sure where to start with debugging this, however is seems that subscript items are matched inside of markup blocks, which I'm not entirely sure is correct. For example:

```org
~TEST ITEM~
~TEST_ITEM~
```

results in the second item being parsed as a subscript. From what I've read, superscripts would be `^{...}` and subscripts would be `_{...}`, right? The above ends up looking like the following (highlighting and concealing via _Neovim_, but test is as noted above):

![image](https://user-images.githubusercontent.com/31262046/144356499-baf3ca3f-ec8d-4e4f-85e7-3b26ca53bd22.png)
 
---

Looks like just plain `^` and `_` are supported as well, but they both require a space after them to be counted as a super/subscript, so the answer to this seems to just be "yes".

I'll probably just have to change the highlighting on my end so things _look_ the same, although the capture groups are actually different. Will leave this open for a bit and close it otherwise, as I believe they are indeed correct.

**Comment by emiasims** [comment]
Thanks for the issue, I am completely changing how the markup parsing is done (moving it to queries/external algorithms, see #13 for way too much detail, or the `markup-redo` branch for the current status in implementation).
