### ISSUE TITLE
Parsing errors with latest plan parsing changes

### ISSUE THREAD

**Issue by kristijanhusak** [milisims/tree-sitter-org#14]
Since the latest commit on main that parses plan dates without checking the exact type (deadline,scheduled,closed), I started getting errors for regular plain content. For example:

```
* TODO Orgmode
  Docs: [[https://orgmode.org/worg/doc.html][Doc]]
```

Parses like this:
```
(document [0, 0] - [2, 0]
  (section [0, 0] - [2, 0]
    (headline [0, 0] - [0, 14]
      (stars [0, 0] - [0, 1])
      (item [0, 2] - [0, 14]))
    (ERROR [1, 2] - [1, 50]
      (name [1, 2] - [1, 7])
      (ERROR [1, 25] - [1, 26])
      (ERROR [1, 38] - [1, 39]))))
test.org	0 ms	(ERROR [1, 2] - [1, 50])
```

Once I remove the `:`, it works fine. 

Seems like `markup-redo` branch takes care of that by checking if the right hand side of expression is a date, but I'm not sure what's the release plan for it.

**Comment by emiasims** [comment]
This one has been an exercise in whack-a-mole
