### ISSUE TITLE
Latex errors out

### ISSUE THREAD

**Issue by joshpetit** [milisims/tree-sitter-org#15]
Hey! So I've had a few problems with using `\[ \]` and `$`. WHen I do this:

```
\[
T(n) = T(n/2) + 2T(n/4) + n,
T(1) = 0
\]
```
it errors out as well as well as:
```
$$
# stuff
$$
```

Is there something wrong with my syntax?

**Comment by emiasims** [comment]
Hey sorry for the delay in response. Check out the markup-redo branch, all within-paragraph parsing is removed in favor of exposing all text as nodes for customization.
