### ISSUE TITLE
Add tree-sitter-org to nvim-treesitter's list of supported languages?

### ISSUE THREAD

**Issue by schoettl** [milisims/tree-sitter-org#18]
It's not yet mentioned here:
https://github.com/nvim-treesitter/nvim-treesitter#supported-languages

Do you think it's ready to add it?

I couldn't test it yet, it's not so easy to install while still having a big .vimrc not compatible with neovim :/

**Comment by emiasims** [comment]
If you have nvim-treesitter installed, all you need is a lua block with:
``` lua
require('nvim-treesitter.parsers').get_parser_configs().org = {
  install_info = {
    url = 'https://github.com/milisims/tree-sitter-org',
    branch = 'main',
    files = { 'src/parser.c', 'src/scanner.cc' },
  },
  filetype = 'org',
}
```

Then you can use `TSInstall org` to install it.

As for adding it to the nvim-treesitter repository, I have not yet done so, it's on my radar though.
