### ISSUE TITLE
Support for markup:  `*bold*`, `/italic/`, `_underlined_`, `=verbatim=`, `~code~` and `+strike-through+`

### ISSUE THREAD

**Issue by joaomsa** [milisims/tree-sitter-org#22]
Is it a non-goal of the project to support markup elements or would you be open to contributions implementing it?

i.e. `*bold*`, `/italic/`, `_underlined_`, `=verbatim=`, `~code~` and `+strike-through+`

Technically in org-mode the characters for each type of markup can be configured through the `org-emphasis-alist` variable [[1][1]], but it doesn't seem very common to radically alter it [[2][2]]. From a cursory glance, people seem to be mostly altering it to change colors.

Supporting markup would be pretty useful for syntax highlighting.

I'm curious what your take on it is, before I start that effort (or maybe you've already have)?

[1]: https://github.com/bzg/org-mode/blob/main/lisp/org.el#L3774
[2]: https://github.com/search?q=%27org-emphasis-alist%27&type=code

**Comment by emiasims** [comment]
It is a non-goal of this project. I had previously implemented them and they were a comparative nightmare to get to function properly. Outside implementation difficulty, there are edge cases like `*/bold-italic/*` is not supported by default, but some people prefer it to be enabled.

So, if you want the markup supported by tree-sitter, it's easier in my opinion to create a secondary parser and inject it into the places we want markup to be parsed.
