### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by kristijanhusak** [milisims/tree-sitter-org#24]
Hi, 

I got an [issue about LaTeX support](https://github.com/nvim-orgmode/orgmode/issues/300), and wanted to check with you what is actually supported? I don't have any LaTeX experience so I can hardly figure it out. From what I tested, only something like this works:
```
\begin{align}
2x - 5y &= 8 \\
3x + 9y &= -12
\end{align}
```

This is an example from here https://orgmode.org/worg/dev/org-syntax.html#LaTeX_Environments, but without the `*` in the `align`, since that causes error in parsing.
Other examples seems to parse like a regular paragraph.

**Comment by gzagatti** [comment]
Following up on my answer in the original issue.

Orgmode syntax says that `\[ ... \]` are objects, but, in practice, they represent equation blocs. Therefore, it would be useful if they could be treated as `latex_env` by the grammar. 

My suggestion would be to modify the [grammar](https://github.com/milisims/tree-sitter-org/blob/aeacac619457a187bb202b9dfc58541232ed4a25/grammar.js#L274) in the following way:

```js
latex_env: $ => choice(
  seq(
    optional($._directive_list),
    caseInsensitive('\\begin{'),
    field('name', alias(/[\p{L}\p{N}]+/, $.name)),
    token.immediate(/\*?}/),
    $._eol,
    optional(field('contents', $.contents)),
    caseInsensitive('\\end{'),
    alias(/[\p{L}\p{N}]+/, $.name),
    token.immediate(/\*?}/),
    $._eol,
  ),
  seq(
    optional($._directive_list),
    '\\[',
    optional(field('contents', $.contents)),
    '\\]',
    $._eol,
  ),
),
```

In essence, we are treating paragraphs which contain a block equation as a LaTex Environment. However, I don't know if that would be the best option, as this is my first time playing with Treesiter.

**Comment by emiasims** [comment]
> but without the `*` in the `align`

This should be allowed, thought I had changed it at some point. Oops. Fixed.

> Orgmode syntax says that \[ ... \] are objects, but, in practice, they represent equation blocs. 

I think that this is reasonable, and I've added it with a few tests. Notably, I'm restrict it to requiring their own newlines:
``` org
\[
a + b &= c
\]
```

This way paragraphs would still exist that could start with a fragment, and it's in line with most other elements.

**Comment by gzagatti** [comment]
Thanks so much! It works very well in conjunction with the vim plugin orgmode.
