### ISSUE TITLE
Empty check boxes are treated as 3 separate expression unlike all other checkboxes

### ISSUE THREAD

**Issue by akinsho** [milisims/tree-sitter-org#27]
Hi 👋🏿 ,

I've been refactoring my plugin https://github.com/akinsho/org-bullets.nvim which is similar to the emacs bullets plugin. I recently switched to identifying nodes to conceal using treesitter (your parser) and that's been working really well except for this issue I just hit.

I've noticed that using `[X]` will return one expr node which I can `#match/#eq` against whereas an empty check box i.e. `[ ]` return 3 expression nodes for each character so matching fails.

I'm guessing this is a bug or workaround of some sort but would be great to have the whole thing returned as a node so I can conceal it.

**Comment by kristijanhusak** [comment]
I'm not sure, but I think you could do something like this https://github.com/milisims/tree-sitter-org/blob/7ab140276cff85bf6dd08914e04188f4da1ff0ab/queries/highlights.scm#L64 .

**Comment by emiasims** [comment]
Hi! The link by @kristijanhusak is the current workaround. Unfortunately, without a custom directive/predicate that can across a range of nodes (the two `expr` nodes: `[` and `]`), the best we can do is matching any `[ ]` with one or more spaces. It's an easy predicate to write, but I'm working on an alternative: I do have a branch with the checkbox as a node but I haven't resolved all of the issues yet. I just pushed it in the `checkbox` branch, so you can use it for now if you like. Specifically, the failing test is `[- anything`, erroring out instead of being a paragraph.

**Comment by akinsho** [comment]
@milisims @kristijanhusak thanks for pointing me towards that 👍🏿 , I'm happy to stick with the main branch as I've already done a fair bit of breakage in that plugin would rather not point people towards a specific branch of the parser. 

Will give the queries you referenced a try, but on a very preliminary test, the linked one doesn't seem to match anything. I'll have a go properly and see. I just dumped it into the playground and checked to see if it'd capture anything

**Comment by emiasims** [comment]
Sorry, apparently there is a workaround:
```
(listitem . (bullet) . (paragraph . (expr "[" "str" @OrgCheckDone "]") @OrgCheckbox (#match? @OrgCheckbox "^\\[[xX]\\]$")))
(listitem . (bullet) . (paragraph . (expr "[" "-" @OrgCheckInProgress "]") @OrgCheckbox (#eq? @OrgCheckbox "[-]")))
(listitem . (bullet) . (paragraph . (expr "[") @OrgCheckbox.left (#eq? @OrgCheckbox.left "[") . (expr "]") @OrgCheckbox.right (#eq? @OrgCheckbox.right "]")) @ignore (#match? @ignore "^\\[ \\]"))
```


The queries in this repository are not really for neovim, specifically because the backslashes need an escape. But otherwise, the paragraph can just be checked with this match for an empty checkbox

**Comment by akinsho** [comment]
@milisims thanks 👍🏿  that worked for the first 2 and matches the empty checkbox but produces two captures 🤔 could just be an oversight on my behalf though

**Comment by emiasims** [comment]
The "captures" in neovim will refer to each `@capture`, so there are multiple captures per "match". So using `iter_matches` is probably what you want, rather than `iter_captures`.

I use this function to print captures and matches when testing queries:
``` lua
function tslib.print_query(query, bufnr, lang)
  local qo
  bufnr = bufnr or 0
  lang = lang or require('nvim-treesitter.parsers').ft_to_lang(vim.o.filetype)
  if vim.startswith(query, '*') then
    qo = vim.treesitter.get_query(lang, query:sub(2))
  else
    qo = vim.treesitter.parse_query(vim.bo.filetype, query)
  end
  local root = vim.treesitter.get_parser(bufnr, lang):parse()[1]:root()
  local capture = {}
  P "Captures"
  for _, node, metadata in qo:iter_captures(root, bufnr, 0, -1) do
    P { node:type(), { node:range() }, metadata }
    table.insert(capture, node)
  end
  P ""
  local i = 0
  for pat, match, metadata in qo:iter_matches(root, bufnr, 0, -1) do
    i = i + 1
    P(string.format("Match: %s", i))
    for id, node in pairs(match) do
      P { pat, id, qo.captures[id], { node:range() }, metadata[id] }
    end
  end
end

function P(v)
  vim.notify(vim.inspect(v))
  return v
end
```

At the command line, you'll have to use additional escapes for the backslashes, or if you've used `set_query`, then you can use it like `print_query('*query_name')`

So the first query would be examined like:
``` vim
lua print_query('(listitem . (bullet) . (paragraph . (expr "[" "str" @OrgCheckDone "]") @OrgCheckbox (#match? @OrgCheckbox "^\\\\[[xX]\\\\]$")))')
```

and will output something like (if it finds 2 checkboxes):
```
"Captures"                                                                                                                                                                                                                                                      
{ "expr", { 22, 4, 22, 7 }, {} }                                                                                                                                                                                                                                
{ "str", { 22, 5, 22, 6 }, {} }                                                                                                                                                                                                                                 
{ "expr", { 23, 4, 23, 7 }, {} }                                                                                                                                                                                                                                
{ "str", { 23, 5, 23, 6 }, {} }                                                                                                                                                                                                                                 
""                                                                                                                                                                                                                                                              
"Match: 1"                                                                                                                                                                                                                                                      
{ 1, 1, "OrgCheckDone", { 22, 5, 22, 6 } }                                                                                                                                                                                                                      
{ 1, 2, "OrgCheckbox", { 22, 4, 22, 7 } }                                                                                                                                                                                                                       
"Match: 2"                                                                                                                                                                                                                                                      
{ 1, 1, "OrgCheckDone", { 23, 5, 23, 6 } }                                                                                                                                                                                                                      
{ 1, 2, "OrgCheckbox", { 23, 4, 23, 7 } }
```

**Comment by akinsho** [comment]
@milisims thanks for going into details and suggesting `iter_matches` I've given it a go and can clearly see the component parts of each match but something I'm still struggling with is an element that exactly matches `[ ]` no prefix, no rest of the line just that segment. I realize with `iter_matches` I can probably reconstruct it, but I would love to avoid edge case logic to handle joining the ranges into one, e.g. merging the `[` range with the `]` range.

So I guess my question is with the query above is it possible to match just that, i.e. a node that represents just that segment (I'm guessing probably not)? Sorry for the back and forth, this is definitely beyond my TS query knowledge.

**Comment by akinsho** [comment]
I decided to just use each brackets range to construct a "node" with a start being the start of the left match and the end of the right match. It's a little horrible, so if you ever merge the branch to create the single node please let me know 🙏🏿 . Gonna close this out for now though

**Comment by emiasims** [comment]
Checkbox branch is now passing all tests. The `(checkbox)` node is either an empty checkbox with no `status` field: `"[ ]" ➜ (checkbox)`, or it must match an `(expr)` without repeat

An expr node matches:
- one symbol: `-`, `/`, `?`, etc
- a number with any number of digits: `1234`
- a string: `x`, `X`, `done` etc

Will not match combinations of those components! For example, `[x1]` would be parsed as part of the `paragraph` of the listitem's contents.

To clarify, if there's no `status` field, then the checkbox is empty.

Since this might break something, I'll wait a couple days before merging.
