### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by lukas-reineke** [milisims/tree-sitter-org#32]
Can you publish this to https://crates.io/ ?

**Comment by lukas-reineke** [comment]
@milisims sorry I don't want to be annoying, but have you considered this?
I'd like to use the grammar as a dependency for my project. But if this is not on crates.io it makes it much more incontinent for me to publish there.
I'd have to include it as a git submodule and manage versions manually.

**Comment by emiasims** [comment]
Sorry I don't move very quickly, but I appreciate the ping. I'll be able to get to it today or more likely tomorrow. It's entirely because I don't know what I'm doing with it.

**Comment by lukas-reineke** [comment]
Thanks a lot. No rush

**Comment by emiasims** [comment]
I published the current main branch (v1.3), thanks for the request and for your patience! I'll be keeping it up to date.

**Comment by lukas-reineke** [comment]
Awesome, thank you
