### ISSUE TITLE
Not compiling via Neovim

### ISSUE THREAD

**Issue by Yabasa** [milisims/tree-sitter-org#33]
I'm new to using org mode in Neovim (and Neovim itself...) so I could be doing something wrong but I'm getting the following error when trying to install the org treesitter parser:

![image](https://user-images.githubusercontent.com/29189365/179805205-f3f51b98-8371-4200-a732-c74727192477.png)

Neovim version: 0.7.2

I simplified my init.vim down to just the Plug install command for treesitter:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
call plug#end()
```

Command in Neovim: `:TSInstall org`

This project is awesome, thanks for working on it!

**Comment by emiasims** [comment]
Try adding this:
``` lua
require('nvim-treesitter.parsers').get_parser_configs().org = {
  install_info = {
    url = 'https://github.com/milisims/tree-sitter-org',
    branch = 'main',
    files = { 'src/parser.c', 'src/scanner.cc' },
  },
  filetype = 'org',
}
```
Then use `:TSInstall org`. Let me know if that works!

I have been slacking on making a contribution to nvim-treesitter because it's strongly geared around programming languages for the definitions of highlight groups, etc. But I really should take care of it. Bumped up its priority.

**Comment by Yabasa** [comment]
Thanks for the quick response! Yeah I was kinda surprised this exists because I wouldn't have thought of using treesitter for org files but it's a great idea.

That didn't work unfortunately. I inspected that table with and without adding that config it looks pretty much the same at least in terms of the install_info.

Without additional config:
![image](https://user-images.githubusercontent.com/29189365/179822330-93eb807c-5283-4784-8a14-c48111f9ab71.png)

With additional config:
![image](https://user-images.githubusercontent.com/29189365/179822205-84c770f9-3970-492d-a935-a594a6344641.png)

Maybe I should try to build manually using make to see if I can replicate the issue. If so then maybe it's my machine setup.

**Comment by emiasims** [comment]
UINT8_MAX is defined in `stdint.h` which is included by `tree-sitter/parser.h`, so yeah probably something weird about the build setup. If you clone the repository without setting up node, you should be able to run `gcc -o org.so -I./src src/parser.c src/scanner.cc -shared -Os -lstdc++` to compile it.

**Comment by Yabasa** [comment]
I get the exact same error when running that build command directly. So yeah, something with my machine. I don't have root on this machine (at work) so I'll probably just abandon trying use org on it for now. It's quite an old version of RHEL (7.2) so I should request an upgrade first and then try again.

Thanks for the help in narrowing it down quickly!
