### ISSUE TITLE
Fix issue with latest tree-sitter

### ISSUE THREAD

**Issue by kristijanhusak** [milisims/tree-sitter-org#34]
Current Neovim nightly uses latest version of tree-sitter. Entering `*` causes freezing of Neovim, which I reported here https://github.com/nvim-treesitter/nvim-treesitter/issues/3258. Creator of the PR that introduced using HEAD version of tree-sitter says that issue is most likely in `scanner.cc` file here, since tree-sitter introduced some changes.

* Comment that mentions it: https://github.com/nvim-treesitter/nvim-treesitter/issues/3258#issuecomment-1214355346
* Tree-sitter change: https://github.com/tree-sitter/tree-sitter/pull/1783

**Comment by emiasims** [comment]
Wow, nasty. Thanks for reporting.

Fix feels a bit ham-fisted, but there's not a lot of control for error-recovery and the tests went through.
