### ISSUE TITLE
Plan not parsed when line starts with tab

### ISSUE THREAD

**Issue by kristijanhusak** [milisims/tree-sitter-org#36]
Original issue reported here: https://github.com/nvim-orgmode/orgmode/issues/362.

Org content:

```
* TODO Test
	 DEADLINE: <2022-09-10 Sat 15:21>
```

Expected:

```
(document [0, 0] - [2, 0]
  subsection: (section [0, 0] - [2, 0]
    headline: (headline [0, 0] - [1, 0]
      stars: (stars [0, 0] - [0, 1])
      item: (item [0, 2] - [0, 11]
        (expr [0, 2] - [0, 6])
        (expr [0, 7] - [0, 11])))
    plan: (plan [1, 2] - [2, 0]
      (entry [1, 2] - [1, 34]
        name: (entry_name [1, 2] - [1, 10])
        timestamp: (timestamp [1, 12] - [1, 34]
          date: (date [1, 13] - [1, 23])
          day: (day [1, 24] - [1, 27])
          time: (time [1, 28] - [1, 33]))))))
```

Got:

```
(document [0, 0] - [2, 0]
  subsection: (section [0, 0] - [2, 0]
    headline: (headline [0, 0] - [1, 0]
      stars: (stars [0, 0] - [0, 1])
      item: (item [0, 2] - [0, 11]
        (expr [0, 2] - [0, 6])
        (expr [0, 7] - [0, 11])))
    body: (body [1, 0] - [2, 0]
      (paragraph [1, 0] - [2, 0]
        (expr [1, 0] - [1, 1])
        (expr [1, 2] - [1, 11])
        (expr [1, 12] - [1, 23])
        (expr [1, 24] - [1, 27])
        (expr [1, 28] - [1, 34])))))
```

**Comment by jgollenz** [comment]
[Orgmode says](https://orgmode.org/manual/Timestamps.html) that timestamps can appear anywhere in the body of a headline. That does not seem to work:

```
* TODO test

  DEADLINE: <2022-09-12 Mon>
```

results in

```
subsection: section [0, 0] - [3, 0]
  headline: headline [0, 0] - [1, 0]
    stars: stars [0, 0] - [0, 1]
    item: item [0, 2] - [0, 11]
      expr [0, 2] - [0, 6]
      expr [0, 7] - [0, 11]
  body: body [1, 0] - [3, 0]
    paragraph [2, 2] - [3, 0]
      expr [2, 2] - [2, 11]
      expr [2, 12] - [2, 23]
      expr [2, 24] - [2, 28]
```

no timestamp at all. Is this one of the cases where this grammar differs from emacs' parser? If so, do you think it would be a good idea to start tracking those differences for future reference?

**Comment by kristijanhusak** [comment]
There is difference between "plan" timestamps and other timestamps. Plan timestamp needs to appear right after the headline, while other can appear anywhere else.
We are handling that by parsing those manually, but we do miss the highlights. There is probably a way to go around that.

**Comment by jgollenz** [comment]
Ah, I see. Thanks for clarifying :+1:

**Comment by kristijanhusak** [comment]
On that note, @milisims , I would appreciate your help with this. I'm trying to write a highlight query that would match this . I tried with something simple to get me started, but that didn't work out.

I tried this query
```
((expr "<") (expr ">")) @OrgTimestamp
```

with this content:
```
* TODO Test
  content
  <2022-09-13 Tue>
```
But this matches only first expr, which is basically only this part: `<2022-09-13`.

I then tried writing a custom predicate, and it returns true, but it still highlights only this part of the date. (Here's the diff https://github.com/nvim-orgmode/orgmode/compare/task%2Fhighlight-dates-ts?expand=1)

Do you have any idea how can I solve this while leverating neovim highlighter? I know I can write my own logic to add a highlight group, but I'm trying to avoid that if possible. Thanks!
