### ISSUE TITLE
Incomplete date range causes Error

### ISSUE THREAD

**Issue by Maltimore** [milisims/tree-sitter-org#39]
A date range would be something like `<2023-01-26 Thu>--<2023-01-27 Fri>`. Having an incomplete date range like `<2023-01-26 Thu>--` in some parts of the document leads to a parsing error, but not in others:

```
* headline
  <2023-01-26 Thu>--
```
leads to
```
subsection: (section) [1:1-3:0]
 headline: (headline) [1:1-2:0]
  stars: (stars) [1:1-1]
  item: (item) [1:3-10]
   (expr) [1:3-10]
 plan: (plan) [2:3-3:0]
  (entry) [2:3-18]
   timestamp: (timestamp) [2:3-18]
    date: (date) [2:4-13]
    day: (day) [2:15-17]
  (ERROR) [2:19-20]
```
but
```
* headline

  <2023-01-26 Thu>--
```
leads to
```
subsection: (section) [1:1-4:0]
 headline: (headline) [1:1-2:0]
  stars: (stars) [1:1-1]
  item: (item) [1:3-10]
   (expr) [1:3-10]
 body: (body) [2:1-4:0]
  (paragraph) [3:3-4:0]
   (expr) [3:3-13]
   (expr) [3:15-20]
```

**Comment by emiasims** [comment]
This is expected and intended behavior. Only the line after the headline is parsed as a planning line, and it's an error if the date is incomplete. After the empty space, dates are just text.

**Comment by Maltimore** [comment]
Oh, in that case sorry for the noise! Thanks for explaining.

**Comment by tonico** [comment]
I ran into a similar issue.

```
* Some event
  <2023-11-17 Fr> will be fun!
```
The text above produces a parse tree that contains an error (similar as in the comment above). But according to https://orgmode.org/worg/org-syntax.html#Planning the line after the heading is not a planning line because either DEADLINE, SCHEDULED, or CLOSED is required at the start of a planning line.
