### ISSUE TITLE
Table horizontal rule strangely splits table into multiple nodes

### ISSUE THREAD

**Issue by kristijanhusak** [milisims/tree-sitter-org#8]
Hi,

Today I started playing with tables, and noticed one thing I can't really figure out why it's happening.

Having this content:
```
  | Test | Foo  | Bar    |
  |------+------+--------|
  | Test |      | Seven  |
  | dda  | test |        |
  |      |      |        |
  | dda  | test |        |
```

Generates this:
```
(document [0, 2] - [6, 0]
  (body [0, 2] - [6, 0]
    (table [0, 2] - [2, 0]
      (row [0, 2] - [1, 0]
        (cell [0, 2] - [0, 8])
        (cell [0, 9] - [0, 14])
        (cell [0, 16] - [0, 21])))
    (table [2, 2] - [6, 0]
      (row [2, 2] - [3, 0]
        (cell [2, 2] - [2, 8])
        (cell [2, 9] - [2, 10])
        (cell [2, 16] - [2, 23]))
      (row [3, 2] - [4, 0]
        (cell [3, 2] - [3, 7])
        (cell [3, 9] - [3, 15])
        (cell [3, 16] - [3, 17]))
      (row [4, 2] - [5, 0]
        (cell [4, 2] - [4, 3])
        (cell [4, 9] - [4, 10])
        (cell [4, 16] - [4, 17]))
      (row [5, 2] - [6, 0]
        (cell [5, 2] - [5, 7])
        (cell [5, 9] - [5, 15])
        (cell [5, 16] - [5, 17])))))
```

Also, if I add one more hr rule to the table like this:
```
  | Test | Foo  | Bar    |
  |------+------+--------|
  | Test |      | Seven  |
  | dda  | test |        |
  |      |      |        |
  |------+------+--------|
  | dda  | test |        |
```

Generates this:
```
(document [0, 2] - [7, 0]
  (body [0, 2] - [7, 0]
    (table [0, 2] - [3, 0]
      (row [0, 2] - [1, 0]
        (cell [0, 2] - [0, 8])
        (cell [0, 9] - [0, 14])
        (cell [0, 16] - [0, 21]))
      (row [2, 2] - [3, 0]
        (cell [2, 2] - [2, 8])
        (cell [2, 9] - [2, 10])
        (cell [2, 16] - [2, 23])))
    (table [3, 2] - [7, 0]
      (row [3, 2] - [4, 0]
        (cell [3, 2] - [3, 7])
        (cell [3, 9] - [3, 15])
        (cell [3, 16] - [3, 17]))
      (row [4, 2] - [5, 0]
        (cell [4, 2] - [4, 3])
        (cell [4, 9] - [4, 10])
        (cell [4, 16] - [4, 17]))
      (row [6, 2] - [7, 0]
        (cell [6, 2] - [6, 7])
        (cell [6, 9] - [6, 15])
        (cell [6, 16] - [6, 17])))))
```

I would not expect horizontal rule to split the table in any way. I think this should be single table with multiple rows.
Looking at grammar doesn't give me a clue, because there it looks like it can either be a row with valid cells, or hr rule. I can't figure out why it would cause this.

Also, is there a chance to expose the horizontal rule node itself? It's much easier to collect it while parsing the tree instead of figuring it out manually, since I want to introduce reformatting the table on edit, and I also potentially need to shrink/expand the hr rule line.

**Comment by emiasims** [comment]
Okay, this is a weird effect from the dynamic precedence. I'm looking into it, and add `hr` as the horizontal rule node. The issue is unrelated to horizontal rules, and just depends on the number of lines in the table.

**Comment by emiasims** [comment]
This issue also exists with paragraphs. Changing the definition to use `prec.right` over the dynamic prec 'fixes' it but introduces an issue. This is parsed as `(paragraph)` instead of `(paragraph) (drawer)`:
``` org
a
:A:
b
:END:
```
That seems unambiguous to me, so I think it should be parsed appropriately. Unfortunately, any time there's any `(element)` after a paragraph without a newline, with `prec.right`, we'll just get a paragraph. This was the original reason for the use of prec.right. I'll see about figuring it out. 

So, a paragraph over 6 lines will cause this issue in the current branch.

**Comment by kristijanhusak** [comment]
I did notice randomly that drawer is not parsed while implementing clocking. I thought it's something different, but it was probably this issue.
I think properly parsing drawer is more important then parsing the paragraph. Paragraph usually contains plain text that doesn't need to be parsed by itself for any specific reason (at least I didn't had to do it for now).

**Comment by kristijanhusak** [comment]
@milisims I gave this a test, and to me it looks fine as it is. Having this content:
```
* TODO First Task
  DEADLINE: <2021-10-08 Fri>
* TODO Second Task
  DEADLINE: <2021-10-15 Fri>
  Some
  multiline
  content
  that
  spans
  a lot
  of
  lines
  :SOMEDRAWER:
  The
  multiline
  text
  in
  drawer
  that
  is
  more
  than
  6
  lines
  :END:
  Some
  content
  after
  the
  drawer
  more
  than
  6
  lines
```

Creates this tree:
```
(document [0, 0] - [34, 0]
  (section [0, 0] - [2, 0]
    (headline [0, 0] - [0, 17]
      (stars [0, 0] - [0, 1])
      (item [0, 2] - [0, 17]))
    (plan [1, 2] - [2, 0]
      (deadline [1, 2] - [1, 28]
        (timestamp [1, 12] - [1, 28]
          (date [1, 13] - [1, 27])))))
  (section [2, 0] - [34, 0]
    (headline [2, 0] - [2, 18]
      (stars [2, 0] - [2, 1])
      (item [2, 2] - [2, 18]))
    (plan [3, 2] - [4, 0]
      (deadline [3, 2] - [3, 28]
        (timestamp [3, 12] - [3, 28]
          (date [3, 13] - [3, 27]))))
    (body [4, 2] - [34, 0]
      (paragraph [4, 2] - [7, 0])
      (paragraph [7, 2] - [12, 0])
      (drawer [12, 2] - [25, 0])
      (paragraph [25, 2] - [26, 0])
      (paragraph [26, 2] - [34, 0]))))
```

And shorter content (< 6 lines for a paragraph):
```
* TODO First Task
  DEADLINE: <2021-10-08 Fri>
* TODO Second Task
  lines
  :SOMEDRAWER:
  Abc
  :END:
  past
* TODO Third task

```

Also creates 2 separate paragraphs around the drawer:
```
(document [0, 0] - [9, 0]
  (section [0, 0] - [2, 0]
    (headline [0, 0] - [0, 17]
      (stars [0, 0] - [0, 1])
      (item [0, 2] - [0, 17]))
    (plan [1, 2] - [2, 0]
      (deadline [1, 2] - [1, 28]
        (timestamp [1, 12] - [1, 28]
          (date [1, 13] - [1, 27])))))
  (section [2, 0] - [8, 0]
    (headline [2, 0] - [2, 18]
      (stars [2, 0] - [2, 1])
      (item [2, 2] - [2, 18]))
    (body [3, 2] - [8, 0]
      (paragraph [3, 2] - [4, 0])
      (drawer [4, 2] - [7, 0])
      (paragraph [7, 2] - [8, 0])))
  (section [8, 0] - [9, 0]
    (headline [8, 0] - [8, 17]
      (stars [8, 0] - [8, 1])
      (item [8, 2] - [8, 17]))))
```

As I understood from your last comment, drawer should be a child of paragraph. I don't think that's necessary, since i'm getting the drawer with `(body) (drawer @drawer)`, and that works perfectly fine for me. Why do you think it needs to be a child of paragraph?

**Comment by emiasims** [comment]
> This is parsed as `(paragraph)` instead of `(paragraph) (drawer)`:

Sequential, not child. I meant that if I use the resolution to the table problem here, then another issue crops up: the paragraph eating the drawer, which I'm having some difficulty resolving. Like you said, it's not a huge deal for paragraphs to be broken up, but I'm working on it to parse correctly.

**Comment by kristijanhusak** [comment]
Ah, ok. I thought that with current main I would have issues parsing the drawer with 6+ lines in the paragraph, but I don't. Don't let that paragraph eat our drawers :P
