### ISSUE TITLE
"Escaped" text fails to parse and reports an error

### ISSUE THREAD

**Issue by kristijanhusak** [milisims/tree-sitter-org#9]
Hey,

I just got an [issue report on orgmode.nvim repo](https://github.com/kristijanhusak/orgmode.nvim/issues/157) that found a problem with parsing things that are "escaped". For example, with this content:

```
* TODO Test
  This \[is error]
```

I get this:
```
(document [0, 0] - [2, 0]
  (ERROR [0, 0] - [2, 0]
    (headline [0, 0] - [0, 11]
      (stars [0, 0] - [0, 1])
      (item [0, 2] - [0, 11]))))
test.org	0 ms	(ERROR [0, 0] - [2, 0])
```
Backslash before the `[` causes the issue.

Similar thing happens with dot for example:
```
* TODO Test
  This \. Test
```

Output:
```
(document [0, 0] - [2, 0]
  (section [0, 0] - [2, 0]
    (headline [0, 0] - [0, 11]
      (stars [0, 0] - [0, 1])
      (item [0, 2] - [0, 11]))
    (body [1, 2] - [2, 0]
      (paragraph [1, 2] - [2, 0]
        (ERROR [1, 7] - [1, 9]
          (ERROR [1, 8] - [1, 9]))))))
test.org	0 ms	(ERROR [1, 7] - [1, 9])
```

Latter seems more specific than former. Is this because it looks like a regex?

**Comment by emiasims** [comment]
I need to introduce a conflict for matching `\`, (latex fragments, I believe). This should be an easy fix, but it falls into the markdown parsing that I want to export to queries + a possible `tree-sitter-org-markdown` parser that we'd discussed. I have time set aside next week to do some heavy lifting on all that.

**Comment by kristijanhusak** [comment]
Awesome, thanks.
I'm not sure if it's possible, but it would be great to have parsing a bit more "loose". For example, an Emacs orgmode user tested some of his blog posts and got some parsing errors from random text in paragraphs. I'm not sure if this can be solved. Here's the link https://github.com/nvim-orgmode/orgmode/issues/159

**Comment by emiasims** [comment]
Yeah this is exactly the kind of stuff I want to clean up, thank you for the reference. Removing the in-paragraph parsing (or exporting to a secondary parser) should solve a lot of this.

**Comment by tecosaur** [comment]
I don't know if this is of any help, but I've recently (a few days ago) started writing an Org parser for Julia. It's a work in progress, but seems to be working so far using a hybrid recursive decent / linear parsing model. A few caveats do apply, for instance, I have no prior experience with writing parsers, and it's using a bunch of regex.

**Comment by emiasims** [comment]
This issue will be handled by queries in the next big update (see #13 and/or the markup-redo branch).
